import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { FloatingShapes } from "@/components/common/FloatingShapes";
import Header from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import ScrollToTop from "@/components/common/ScrollToTop";

const poppins = Poppins({
    variable: "--font-popiens",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "DropNest",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${poppins.className} antialiased`}>
                <main className="bg-slate-900 min-h-screen text-white overflow-x-hidden">
                    <FloatingShapes />
                    <ScrollToTop />
                    <Header />
                    {children}
                    <Footer />
                </main>
            </body>
        </html>
    );
}
